In [1]:
import pandas as pd

In [2]:
gender = pd.read_csv("gender.csv")
math = pd.read_csv("math.csv")

In [3]:
%timeit pd.merge(gender,math,how='inner', on="DBN")

726 ms ± 7.29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]:
gender.set_index('DBN', inplace=True)
math.set_index('DBN', inplace=True)

In [5]:
%timeit pd.merge(gender,math,how='inner', on="DBN")

341 ms ± 3.06 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]:
%timeit pd.merge(gender,math,how='inner', left_index=True, right_index=True)

324 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [23]:
pd.merge(gender,math,how='inner', left_index=True, right_index=True)

,School Name,Grade_x,Year_x,Category_x,Number Tested_x,Mean Scale Score_x,Level1_N,Level1_%,Level2_N,Level2_%,...,Level 1 #,Level 1 %,Level 2 #,Level 2 %,Level 3 #,Level 3 %,Level 4 #,Level 4 %,Level 3+4 #,Level 3+4 %
DBN,,,,,,,,,,,,,,,,,,,,,
01M015,PS 015 ROBERTO CLEMENTE,3,2013,Female,12,285,7,58.3,5,41.7,...,2.0,5.1,11.0,28.2,20.0,51.3,6.0,15.4,26.0,66.7
01M015,PS 015 ROBERTO CLEMENTE,3,2013,Female,12,285,7,58.3,5,41.7,...,2.0,6.5,3.0,9.7,22.0,71.0,4.0,12.9,26.0,83.9
01M015,PS 015 ROBERTO CLEMENTE,3,2013,Female,12,285,7,58.3,5,41.7,...,0.0,0.0,6.0,16.2,29.0,78.4,2.0,5.4,31.0,83.8
01M015,PS 015 ROBERTO CLEMENTE,3,2013,Female,12,285,7,58.3,5,41.7,...,0.0,0.0,4.0,12.1,28.0,84.8,1.0,3.0,29.0,87.9
01M015,PS 015 ROBERTO CLEMENTE,3,2013,Female,12,285,7,58.3,5,41.7,...,6.0,23.1,12.0,46.2,6.0,23.1,2.0,7.7,8.0,30.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32K554,ALL CITY LEADERSHIP SECONDARY SCHOOL,All Grades,2017,Male,70,332,0,0.0,10,14.3,...,7.0,6.6,23.0,21.7,69.0,65.1,7.0,6.6,76.0,71.7
32K554,ALL CITY LEADERSHIP SECONDARY SCHOOL,All Grades,2017,Male,70,332,0,0.0,10,14.3,...,2.0,1.9,12.0,11.1,84.0,77.8,10.0,9.3,94.0,87.0
32K554,ALL CITY LEADERSHIP SECONDARY SCHOOL,All Grades,2017,Male,70,332,0,0.0,10,14.3,...,1.0,1.1,7.0,8.0,65.0,74.7,14.0,16.1,79.0,90.8
32K554,ALL CITY LEADERSHIP SECONDARY SCHOOL,All Grades,2017,Male,70,332,0,0.0,10,14.3,...,0.0,0.0,25.0,27.8,45.0,50.0,20.0,22.2,65.0,72.2
32K554,ALL CITY LEADERSHIP SECONDARY SCHOOL,All Grades,2017,Male,70,332,0,0.0,10,14.3,...,0.0,0.0,13.0,13.5,55.0,57.3,28.0,29.2,83.0,86.5

Conclusion: index join speed up by 2x!!!

In [7]:
%timeit gender.join(math, on="DBN", how='inner', lsuffix='_x', rsuffix='_y')

327 ms ± 2.15 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)